-- ============================================================================
-- PHẦN 1: CÀI ĐẶT MÔI TRƯỜNG & QUẢN LÝ TRUY CẬP
-- ============================================================================
-- TPC-H Analytics Project - Database Setup, Roles, Stages, and Data Loading
-- ============================================================================

-- ============================================================================
-- 1.1 TẠO ROLES VÀ PHÂN QUYỀN
-- ============================================================================

-- Tạo các roles cho dự án
CREATE OR REPLACE ROLE TPCH_ADMIN;
CREATE OR REPLACE ROLE TPCH_DEVELOPER;
CREATE OR REPLACE ROLE TPCH_ANALYST;
CREATE OR REPLACE ROLE TPCH_VIEWER;

-- Grant quyền sử dụng warehouse (giả sử đã có warehouse, nếu chưa cần tạo)
-- GRANT USAGE ON WAREHOUSE <warehouse_name> TO ROLE TPCH_ADMIN;
-- GRANT USAGE ON WAREHOUSE <warehouse_name> TO ROLE TPCH_DEVELOPER;
-- GRANT USAGE ON WAREHOUSE <warehouse_name> TO ROLE TPCH_ANALYST;

-- ============================================================================
-- 1.2 TẠO DATABASE VÀ SCHEMAS
-- ============================================================================

-- Tạo database cho dự án
CREATE OR REPLACE DATABASE TPCH_ANALYTICS_DB;
USE DATABASE TPCH_ANALYTICS_DB;

-- Tạo các schemas
CREATE OR REPLACE SCHEMA TPCH_ANALYTICS_DB.STAGING;
CREATE OR REPLACE SCHEMA TPCH_ANALYTICS_DB.SILVER;
CREATE OR REPLACE SCHEMA TPCH_ANALYTICS_DB.GOLD;
CREATE OR REPLACE SCHEMA TPCH_ANALYTICS_DB.ANALYTICS;
CREATE OR REPLACE SCHEMA TPCH_ANALYTICS_DB.REPORTS;
CREATE OR REPLACE SCHEMA TPCH_ANALYTICS_DB.UDFS;

-- Grant quyền trên database cho các roles
GRANT USAGE ON DATABASE TPCH_ANALYTICS_DB TO ROLE TPCH_ADMIN;
GRANT OWNERSHIP ON DATABASE TPCH_ANALYTICS_DB TO ROLE TPCH_ADMIN;

-- Grant quyền trên schemas
-- ADMIN: Full access
GRANT ALL ON SCHEMA TPCH_ANALYTICS_DB.STAGING TO ROLE TPCH_ADMIN;
GRANT ALL ON SCHEMA TPCH_ANALYTICS_DB.SILVER TO ROLE TPCH_ADMIN;
GRANT ALL ON SCHEMA TPCH_ANALYTICS_DB.GOLD TO ROLE TPCH_ADMIN;
GRANT ALL ON SCHEMA TPCH_ANALYTICS_DB.ANALYTICS TO ROLE TPCH_ADMIN;
GRANT ALL ON SCHEMA TPCH_ANALYTICS_DB.REPORTS TO ROLE TPCH_ADMIN;
GRANT ALL ON SCHEMA TPCH_ANALYTICS_DB.UDFS TO ROLE TPCH_ADMIN;

-- DEVELOPER: Read/Write trên STAGING, SILVER; Read trên GOLD
GRANT USAGE ON SCHEMA TPCH_ANALYTICS_DB.STAGING TO ROLE TPCH_DEVELOPER;
GRANT CREATE TABLE ON SCHEMA TPCH_ANALYTICS_DB.STAGING TO ROLE TPCH_DEVELOPER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA TPCH_ANALYTICS_DB.STAGING TO ROLE TPCH_DEVELOPER;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA TPCH_ANALYTICS_DB.STAGING TO ROLE TPCH_DEVELOPER;

GRANT USAGE ON SCHEMA TPCH_ANALYTICS_DB.SILVER TO ROLE TPCH_DEVELOPER;
GRANT CREATE TABLE ON SCHEMA TPCH_ANALYTICS_DB.SILVER TO ROLE TPCH_DEVELOPER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA TPCH_ANALYTICS_DB.SILVER TO ROLE TPCH_DEVELOPER;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA TPCH_ANALYTICS_DB.SILVER TO ROLE TPCH_DEVELOPER;

GRANT USAGE ON SCHEMA TPCH_ANALYTICS_DB.GOLD TO ROLE TPCH_DEVELOPER;
GRANT SELECT ON ALL TABLES IN SCHEMA TPCH_ANALYTICS_DB.GOLD TO ROLE TPCH_DEVELOPER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA TPCH_ANALYTICS_DB.GOLD TO ROLE TPCH_DEVELOPER;

GRANT USAGE ON SCHEMA TPCH_ANALYTICS_DB.ANALYTICS TO ROLE TPCH_DEVELOPER;
GRANT ALL ON SCHEMA TPCH_ANALYTICS_DB.ANALYTICS TO ROLE TPCH_DEVELOPER;

GRANT USAGE ON SCHEMA TPCH_ANALYTICS_DB.UDFS TO ROLE TPCH_DEVELOPER;
GRANT USAGE ON ALL FUNCTIONS IN SCHEMA TPCH_ANALYTICS_DB.UDFS TO ROLE TPCH_DEVELOPER;

-- ANALYST: Read trên tất cả schemas
GRANT USAGE ON SCHEMA TPCH_ANALYTICS_DB.STAGING TO ROLE TPCH_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA TPCH_ANALYTICS_DB.STAGING TO ROLE TPCH_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA TPCH_ANALYTICS_DB.STAGING TO ROLE TPCH_ANALYST;

GRANT USAGE ON SCHEMA TPCH_ANALYTICS_DB.SILVER TO ROLE TPCH_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA TPCH_ANALYTICS_DB.SILVER TO ROLE TPCH_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA TPCH_ANALYTICS_DB.SILVER TO ROLE TPCH_ANALYST;

GRANT USAGE ON SCHEMA TPCH_ANALYTICS_DB.GOLD TO ROLE TPCH_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA TPCH_ANALYTICS_DB.GOLD TO ROLE TPCH_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA TPCH_ANALYTICS_DB.GOLD TO ROLE TPCH_ANALYST;

GRANT USAGE ON SCHEMA TPCH_ANALYTICS_DB.ANALYTICS TO ROLE TPCH_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA TPCH_ANALYTICS_DB.ANALYTICS TO ROLE TPCH_ANALYST;

GRANT USAGE ON SCHEMA TPCH_ANALYTICS_DB.REPORTS TO ROLE TPCH_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA TPCH_ANALYTICS_DB.REPORTS TO ROLE TPCH_ANALYST;

-- VIEWER: Chỉ đọc trên REPORTS
GRANT USAGE ON SCHEMA TPCH_ANALYTICS_DB.REPORTS TO ROLE TPCH_VIEWER;
GRANT SELECT ON ALL TABLES IN SCHEMA TPCH_ANALYTICS_DB.REPORTS TO ROLE TPCH_VIEWER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA TPCH_ANALYTICS_DB.REPORTS TO ROLE TPCH_VIEWER;

-- ============================================================================
-- 1.3 TẠO STAGES
-- ============================================================================

USE SCHEMA TPCH_ANALYTICS_DB.STAGING;

-- Tạo internal stage cho data files
CREATE OR REPLACE STAGE TPCH_DATA_STAGE
    FILE_FORMAT = (TYPE = CSV 
                   FIELD_DELIMITER = ',' 
                   SKIP_HEADER = 1
                   FIELD_OPTIONALLY_ENCLOSED_BY = '"'
                   ESCAPE_UNENCLOSED_FIELD = '\\'
                   TRIM_SPACE = TRUE
                   ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
                   REPLACE_INVALID_CHARACTERS = TRUE);

-- Grant quyền trên stage
GRANT READ ON STAGE TPCH_DATA_STAGE TO ROLE TPCH_ADMIN;
GRANT READ ON STAGE TPCH_DATA_STAGE TO ROLE TPCH_DEVELOPER;
GRANT READ ON STAGE TPCH_DATA_STAGE TO ROLE TPCH_ANALYST;

-- ============================================================================
-- 1.4 TẠO CÁC BẢNG RAW (BRONZE LAYER)
-- ============================================================================

USE SCHEMA TPCH_ANALYTICS_DB.STAGING;

-- Bảng 1: REGION
CREATE OR REPLACE TABLE TPCH_ANALYTICS_DB.STAGING.REGION (
    R_REGIONKEY NUMBER(38,0) PRIMARY KEY,
    R_NAME VARCHAR(25),
    R_COMMENT VARCHAR(152)
);

-- Bảng 2: NATION
CREATE OR REPLACE TABLE TPCH_ANALYTICS_DB.STAGING.NATION (
    N_NATIONKEY NUMBER(38,0) PRIMARY KEY,
    N_NAME VARCHAR(25),
    N_REGIONKEY NUMBER(38,0),
    N_COMMENT VARCHAR(152)
);

-- Bảng 3: CUSTOMER
CREATE OR REPLACE TABLE TPCH_ANALYTICS_DB.STAGING.CUSTOMER (
    C_CUSTKEY NUMBER(38,0) PRIMARY KEY,
    C_NAME VARCHAR(25),
    C_ADDRESS VARCHAR(40),
    C_NATIONKEY NUMBER(38,0),
    C_PHONE VARCHAR(15),
    C_ACCTBAL NUMBER(12,2),
    C_MKTSEGMENT VARCHAR(10),
    C_COMMENT VARCHAR(117)
);

-- Bảng 4: SUPPLIER
CREATE OR REPLACE TABLE TPCH_ANALYTICS_DB.STAGING.SUPPLIER (
    S_SUPPKEY NUMBER(38,0) PRIMARY KEY,
    S_NAME VARCHAR(25),
    S_ADDRESS VARCHAR(40),
    S_NATIONKEY NUMBER(38,0),
    S_PHONE VARCHAR(15),
    S_ACCTBAL NUMBER(12,2),
    S_COMMENT VARCHAR(101)
);

-- Bảng 5: PART
CREATE OR REPLACE TABLE TPCH_ANALYTICS_DB.STAGING.PART (
    P_PARTKEY NUMBER(38,0) PRIMARY KEY,
    P_NAME VARCHAR(55),
    P_MFGR VARCHAR(25),
    P_BRAND VARCHAR(10),
    P_TYPE VARCHAR(25),
    P_SIZE NUMBER(38,0),
    P_CONTAINER VARCHAR(10),
    P_RETAILPRICE NUMBER(12,2),
    P_COMMENT VARCHAR(23)
);

-- Bảng 6: PARTSUPP
CREATE OR REPLACE TABLE TPCH_ANALYTICS_DB.STAGING.PARTSUPP (
    PS_PARTKEY NUMBER(38,0),
    PS_SUPPKEY NUMBER(38,0),
    PS_AVAILQTY NUMBER(38,0),
    PS_SUPPLYCOST NUMBER(12,2),
    PS_COMMENT VARCHAR(199),
    PRIMARY KEY (PS_PARTKEY, PS_SUPPKEY)
);

-- Bảng 7: ORDERS
CREATE OR REPLACE TABLE TPCH_ANALYTICS_DB.STAGING.ORDERS (
    O_ORDERKEY NUMBER(38,0) PRIMARY KEY,
    O_CUSTKEY NUMBER(38,0),
    O_ORDERSTATUS VARCHAR(1),
    O_TOTALPRICE NUMBER(12,2),
    O_ORDERDATE DATE,
    O_ORDERPRIORITY VARCHAR(15),
    O_CLERK VARCHAR(15),
    O_SHIPPRIORITY NUMBER(38,0),
    O_COMMENT VARCHAR(79)
);

-- Bảng 8: LINEITEM
CREATE OR REPLACE TABLE TPCH_ANALYTICS_DB.STAGING.LINEITEM (
    L_ORDERKEY NUMBER(38,0),
    L_PARTKEY NUMBER(38,0),
    L_SUPPKEY NUMBER(38,0),
    L_LINENUMBER NUMBER(38,0),
    L_QUANTITY NUMBER(12,2),
    L_EXTENDEDPRICE NUMBER(12,2),
    L_DISCOUNT NUMBER(12,2),
    L_TAX NUMBER(12,2),
    L_RETURNFLAG VARCHAR(1),
    L_LINESTATUS VARCHAR(1),
    L_SHIPDATE DATE,
    L_COMMITDATE DATE,
    L_RECEIPTDATE DATE,
    L_SHIPINSTRUCT VARCHAR(25),
    L_SHIPMODE VARCHAR(10),
    L_COMMENT VARCHAR(44),
    PRIMARY KEY (L_ORDERKEY, L_LINENUMBER)
);

-- ============================================================================
-- 1.5 LOAD DỮ LIỆU TỪ FILES VÀO TABLES
-- ============================================================================

-- LƯU Ý: Trước khi chạy các lệnh COPY INTO, bạn cần upload các file CSV lên stage
-- Có thể sử dụng SnowSQL hoặc Snowsight UI để upload:
-- 
-- SnowSQL command:
-- PUT file://D:/Snowflake/TPC-H Project/data/tpch_sf1_region.csv @TPCH_DATA_STAGE;
-- PUT file://D:/Snowflake/TPC-H Project/data/tpch_sf1_nation.csv @TPCH_DATA_STAGE;
-- PUT file://D:/Snowflake/TPC-H Project/data/tpch_sf1_customer.csv @TPCH_DATA_STAGE;
-- PUT file://D:/Snowflake/TPC-H Project/data/tpch_sf1_supplier.csv @TPCH_DATA_STAGE;
-- PUT file://D:/Snowflake/TPC-H Project/data/tpch_sf1_part.csv @TPCH_DATA_STAGE;
-- PUT file://D:/Snowflake/TPC-H Project/data/tpch_sf1_partsupp.csv @TPCH_DATA_STAGE;
-- PUT file://D:/Snowflake/TPC-H Project/data/tpch_sf1_orders.csv @TPCH_DATA_STAGE;
-- PUT file://D:/Snowflake/TPC-H Project/data/tpch_sf1_line_item.csv @TPCH_DATA_STAGE;

-- Verify files đã upload
LIST @TPCH_DATA_STAGE;

-- Load data từ stage vào tables
-- REGION
COPY INTO TPCH_ANALYTICS_DB.STAGING.REGION
FROM @TPCH_DATA_STAGE/tpch_sf1_region.csv
FILE_FORMAT = (TYPE = CSV 
               FIELD_DELIMITER = ',' 
               SKIP_HEADER = 1
               FIELD_OPTIONALLY_ENCLOSED_BY = '"'
               ESCAPE_UNENCLOSED_FIELD = '\\'
               TRIM_SPACE = TRUE
               ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
               REPLACE_INVALID_CHARACTERS = TRUE)
ON_ERROR = 'ABORT_STATEMENT';

-- NATION
COPY INTO TPCH_ANALYTICS_DB.STAGING.NATION
FROM @TPCH_DATA_STAGE/tpch_sf1_nation.csv
FILE_FORMAT = (TYPE = CSV 
               FIELD_DELIMITER = ',' 
               SKIP_HEADER = 1
               FIELD_OPTIONALLY_ENCLOSED_BY = '"'
               ESCAPE_UNENCLOSED_FIELD = '\\'
               TRIM_SPACE = TRUE
               ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
               REPLACE_INVALID_CHARACTERS = TRUE)
ON_ERROR = 'ABORT_STATEMENT';

-- CUSTOMER
COPY INTO TPCH_ANALYTICS_DB.STAGING.CUSTOMER
FROM @TPCH_DATA_STAGE/tpch_sf1_customer.csv
FILE_FORMAT = (TYPE = CSV 
               FIELD_DELIMITER = ',' 
               SKIP_HEADER = 1
               FIELD_OPTIONALLY_ENCLOSED_BY = '"'
               ESCAPE_UNENCLOSED_FIELD = '\\'
               TRIM_SPACE = TRUE
               ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
               REPLACE_INVALID_CHARACTERS = TRUE)
ON_ERROR = 'ABORT_STATEMENT';

-- SUPPLIER
COPY INTO TPCH_ANALYTICS_DB.STAGING.SUPPLIER
FROM @TPCH_DATA_STAGE/tpch_sf1_supplier.csv
FILE_FORMAT = (TYPE = CSV 
               FIELD_DELIMITER = ',' 
               SKIP_HEADER = 1
               FIELD_OPTIONALLY_ENCLOSED_BY = '"'
               ESCAPE_UNENCLOSED_FIELD = '\\'
               TRIM_SPACE = TRUE
               ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
               REPLACE_INVALID_CHARACTERS = TRUE)
ON_ERROR = 'ABORT_STATEMENT';

-- PART
COPY INTO TPCH_ANALYTICS_DB.STAGING.PART
FROM @TPCH_DATA_STAGE/tpch_sf1_part.csv
FILE_FORMAT = (TYPE = CSV 
               FIELD_DELIMITER = ',' 
               SKIP_HEADER = 1
               FIELD_OPTIONALLY_ENCLOSED_BY = '"'
               ESCAPE_UNENCLOSED_FIELD = '\\'
               TRIM_SPACE = TRUE
               ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
               REPLACE_INVALID_CHARACTERS = TRUE)
ON_ERROR = 'ABORT_STATEMENT';

-- PARTSUPP
COPY INTO TPCH_ANALYTICS_DB.STAGING.PARTSUPP
FROM @TPCH_DATA_STAGE/tpch_sf1_partsupp.csv
FILE_FORMAT = (TYPE = CSV 
               FIELD_DELIMITER = ',' 
               SKIP_HEADER = 1
               FIELD_OPTIONALLY_ENCLOSED_BY = '"'
               ESCAPE_UNENCLOSED_FIELD = '\\'
               TRIM_SPACE = TRUE
               ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
               REPLACE_INVALID_CHARACTERS = TRUE)
ON_ERROR = 'ABORT_STATEMENT';

-- ORDERS
COPY INTO TPCH_ANALYTICS_DB.STAGING.ORDERS
FROM @TPCH_DATA_STAGE/tpch_sf1_orders.csv
FILE_FORMAT = (TYPE = CSV 
               FIELD_DELIMITER = ',' 
               SKIP_HEADER = 1
               FIELD_OPTIONALLY_ENCLOSED_BY = '"'
               ESCAPE_UNENCLOSED_FIELD = '\\'
               TRIM_SPACE = TRUE
               ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
               REPLACE_INVALID_CHARACTERS = TRUE)
ON_ERROR = 'ABORT_STATEMENT';

-- LINEITEM
COPY INTO TPCH_ANALYTICS_DB.STAGING.LINEITEM
FROM @TPCH_DATA_STAGE/tpch_sf1_line_item.csv
FILE_FORMAT = (TYPE = CSV 
               FIELD_DELIMITER = ',' 
               SKIP_HEADER = 1
               FIELD_OPTIONALLY_ENCLOSED_BY = '"'
               ESCAPE_UNENCLOSED_FIELD = '\\'
               TRIM_SPACE = TRUE
               ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
               REPLACE_INVALID_CHARACTERS = TRUE)
ON_ERROR = 'ABORT_STATEMENT';

-- ============================================================================
-- 1.6 KIỂM TRA DỮ LIỆU VÀ PHÂN QUYỀN
-- ============================================================================

-- Kiểm tra số lượng records trong mỗi bảng
SELECT 'REGION' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM TPCH_ANALYTICS_DB.STAGING.REGION
UNION ALL
SELECT 'NATION', COUNT(*) FROM TPCH_ANALYTICS_DB.STAGING.NATION
UNION ALL
SELECT 'CUSTOMER', COUNT(*) FROM TPCH_ANALYTICS_DB.STAGING.CUSTOMER
UNION ALL
SELECT 'SUPPLIER', COUNT(*) FROM TPCH_ANALYTICS_DB.STAGING.SUPPLIER
UNION ALL
SELECT 'PART', COUNT(*) FROM TPCH_ANALYTICS_DB.STAGING.PART
UNION ALL
SELECT 'PARTSUPP', COUNT(*) FROM TPCH_ANALYTICS_DB.STAGING.PARTSUPP
UNION ALL
SELECT 'ORDERS', COUNT(*) FROM TPCH_ANALYTICS_DB.STAGING.ORDERS
UNION ALL
SELECT 'LINEITEM', COUNT(*) FROM TPCH_ANALYTICS_DB.STAGING.LINEITEM
ORDER BY TABLE_NAME;

-- Sample data từ các bảng
SELECT * FROM TPCH_ANALYTICS_DB.STAGING.REGION LIMIT 5;
SELECT * FROM TPCH_ANALYTICS_DB.STAGING.NATION LIMIT 5;
SELECT * FROM TPCH_ANALYTICS_DB.STAGING.CUSTOMER LIMIT 5;

-- Kiểm tra roles và quyền đã được grant
SHOW GRANTS TO ROLE TPCH_ADMIN;
SHOW GRANTS TO ROLE TPCH_DEVELOPER;
SHOW GRANTS TO ROLE TPCH_ANALYST;
SHOW GRANTS TO ROLE TPCH_VIEWER;

-- Kiểm tra các bảng đã tạo
SHOW TABLES IN SCHEMA TPCH_ANALYTICS_DB.STAGING;

