-- ============================================================================
-- PHẦN 3: KHÁM PHÁ & KIỂM TRA DỮ LIỆU
-- ============================================================================
-- TPC-H Analytics Project - Data Profiling, Quality Checks, Performance Analysis
-- ============================================================================

USE DATABASE TPCH_ANALYTICS_DB;

-- ============================================================================
-- 3.1 DATA PROFILING - KHÁM PHÁ DỮ LIỆU
-- ============================================================================

USE SCHEMA TPCH_ANALYTICS_DB.STAGING;

-- 1. Đếm số dòng mỗi bảng
SELECT 'REGION' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM TPCH_ANALYTICS_DB.STAGING.REGION
UNION ALL
SELECT 'NATION', COUNT(*) FROM TPCH_ANALYTICS_DB.STAGING.NATION
UNION ALL
SELECT 'CUSTOMER', COUNT(*) FROM TPCH_ANALYTICS_DB.STAGING.CUSTOMER
UNION ALL
SELECT 'SUPPLIER', COUNT(*) FROM TPCH_ANALYTICS_DB.STAGING.SUPPLIER
UNION ALL
SELECT 'PART', COUNT(*) FROM TPCH_ANALYTICS_DB.STAGING.PART
UNION ALL
SELECT 'PARTSUPP', COUNT(*) FROM TPCH_ANALYTICS_DB.STAGING.PARTSUPP
UNION ALL
SELECT 'ORDERS', COUNT(*) FROM TPCH_ANALYTICS_DB.STAGING.ORDERS
UNION ALL
SELECT 'LINEITEM', COUNT(*) FROM TPCH_ANALYTICS_DB.STAGING.LINEITEM
ORDER BY TABLE_NAME;

-- 2. Phân tích khách hàng theo quốc gia
SELECT 
    N.N_NAME AS COUNTRY,
    R.R_NAME AS REGION,
    COUNT(DISTINCT C.C_CUSTKEY) AS CUSTOMER_COUNT,
    AVG(C.C_ACCTBAL) AS AVG_ACCOUNT_BALANCE,
    SUM(C.C_ACCTBAL) AS TOTAL_ACCOUNT_BALANCE
FROM TPCH_ANALYTICS_DB.STAGING.CUSTOMER C
JOIN TPCH_ANALYTICS_DB.STAGING.NATION N ON C.C_NATIONKEY = N.N_NATIONKEY
JOIN TPCH_ANALYTICS_DB.STAGING.REGION R ON N.N_REGIONKEY = R.R_REGIONKEY
GROUP BY N.N_NAME, R.R_NAME
ORDER BY CUSTOMER_COUNT DESC;

-- 3. Phân tích đơn hàng theo trạng thái
SELECT 
    O_ORDERSTATUS,
    CASE O_ORDERSTATUS
        WHEN 'F' THEN 'Final'
        WHEN 'O' THEN 'Ordered'
        WHEN 'P' THEN 'Pending'
        ELSE 'Unknown'
    END AS STATUS_DESCRIPTION,
    COUNT(*) AS ORDER_COUNT,
    SUM(O_TOTALPRICE) AS TOTAL_REVENUE,
    AVG(O_TOTALPRICE) AS AVG_ORDER_VALUE,
    MIN(O_TOTALPRICE) AS MIN_ORDER_VALUE,
    MAX(O_TOTALPRICE) AS MAX_ORDER_VALUE
FROM TPCH_ANALYTICS_DB.STAGING.ORDERS
GROUP BY O_ORDERSTATUS
ORDER BY ORDER_COUNT DESC;

-- 4. Top 10 sản phẩm được bán nhiều nhất
SELECT 
    P.P_NAME AS PRODUCT_NAME,
    P.P_BRAND AS BRAND,
    P.P_TYPE AS TYPE,
    SUM(L.L_QUANTITY) AS TOTAL_QUANTITY_SOLD,
    COUNT(DISTINCT L.L_ORDERKEY) AS ORDER_COUNT,
    SUM(L.L_EXTENDEDPRICE) AS TOTAL_REVENUE
FROM TPCH_ANALYTICS_DB.STAGING.LINEITEM L
JOIN TPCH_ANALYTICS_DB.STAGING.PART P ON L.L_PARTKEY = P.P_PARTKEY
GROUP BY P.P_NAME, P.P_BRAND, P.P_TYPE
ORDER BY TOTAL_QUANTITY_SOLD DESC
LIMIT 10;

-- 5. Phân tích đơn hàng theo năm
SELECT 
    YEAR(O_ORDERDATE) AS ORDER_YEAR,
    QUARTER(O_ORDERDATE) AS ORDER_QUARTER,
    COUNT(*) AS ORDER_COUNT,
    COUNT(DISTINCT O_CUSTKEY) AS UNIQUE_CUSTOMERS,
    SUM(O_TOTALPRICE) AS TOTAL_REVENUE,
    AVG(O_TOTALPRICE) AS AVG_ORDER_VALUE
FROM TPCH_ANALYTICS_DB.STAGING.ORDERS
GROUP BY YEAR(O_ORDERDATE), QUARTER(O_ORDERDATE)
ORDER BY ORDER_YEAR DESC, ORDER_QUARTER DESC;

-- 6. Phân tích khách hàng theo market segment
SELECT 
    C_MKTSEGMENT,
    COUNT(*) AS CUSTOMER_COUNT,
    AVG(C_ACCTBAL) AS AVG_ACCOUNT_BALANCE,
    MIN(C_ACCTBAL) AS MIN_ACCOUNT_BALANCE,
    MAX(C_ACCTBAL) AS MAX_ACCOUNT_BALANCE
FROM TPCH_ANALYTICS_DB.STAGING.CUSTOMER
GROUP BY C_MKTSEGMENT
ORDER BY CUSTOMER_COUNT DESC;

-- 7. Top 10 nhà cung cấp theo doanh thu
SELECT 
    S.S_NAME AS SUPPLIER_NAME,
    N.N_NAME AS NATION,
    COUNT(DISTINCT L.L_ORDERKEY) AS ORDER_COUNT,
    SUM(L.L_EXTENDEDPRICE) AS TOTAL_REVENUE,
    AVG(PS.PS_SUPPLYCOST) AS AVG_SUPPLY_COST
FROM TPCH_ANALYTICS_DB.STAGING.LINEITEM L
JOIN TPCH_ANALYTICS_DB.STAGING.SUPPLIER S ON L.L_SUPPKEY = S.S_SUPPKEY
JOIN TPCH_ANALYTICS_DB.STAGING.NATION N ON S.S_NATIONKEY = N.N_NATIONKEY
JOIN TPCH_ANALYTICS_DB.STAGING.PARTSUPP PS ON L.L_PARTKEY = PS.PS_PARTKEY AND L.L_SUPPKEY = PS.PS_SUPPKEY
GROUP BY S.S_NAME, N.N_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;

-- ============================================================================
-- 3.2 DATA QUALITY CHECKS
-- ============================================================================

-- Kiểm tra NULL values trong các bảng quan trọng
-- CUSTOMER
SELECT 
    'CUSTOMER' AS TABLE_NAME,
    SUM(CASE WHEN C_CUSTKEY IS NULL THEN 1 ELSE 0 END) AS NULL_CUSTKEY,
    SUM(CASE WHEN C_NAME IS NULL THEN 1 ELSE 0 END) AS NULL_NAME,
    SUM(CASE WHEN C_NATIONKEY IS NULL THEN 1 ELSE 0 END) AS NULL_NATIONKEY,
    SUM(CASE WHEN C_ACCTBAL IS NULL THEN 1 ELSE 0 END) AS NULL_ACCTBAL,
    COUNT(*) AS TOTAL_ROWS
FROM TPCH_ANALYTICS_DB.STAGING.CUSTOMER

UNION ALL

-- ORDERS
SELECT 
    'ORDERS' AS TABLE_NAME,
    SUM(CASE WHEN O_ORDERKEY IS NULL THEN 1 ELSE 0 END) AS NULL_ORDERKEY,
    SUM(CASE WHEN O_CUSTKEY IS NULL THEN 1 ELSE 0 END) AS NULL_CUSTKEY,
    SUM(CASE WHEN O_ORDERDATE IS NULL THEN 1 ELSE 0 END) AS NULL_ORDERDATE,
    SUM(CASE WHEN O_TOTALPRICE IS NULL THEN 1 ELSE 0 END) AS NULL_TOTALPRICE,
    COUNT(*) AS TOTAL_ROWS
FROM TPCH_ANALYTICS_DB.STAGING.ORDERS

UNION ALL

-- LINEITEM
SELECT 
    'LINEITEM' AS TABLE_NAME,
    SUM(CASE WHEN L_ORDERKEY IS NULL THEN 1 ELSE 0 END) AS NULL_ORDERKEY,
    SUM(CASE WHEN L_PARTKEY IS NULL THEN 1 ELSE 0 END) AS NULL_PARTKEY,
    SUM(CASE WHEN L_EXTENDEDPRICE IS NULL THEN 1 ELSE 0 END) AS NULL_EXTENDEDPRICE,
    SUM(CASE WHEN L_QUANTITY IS NULL THEN 1 ELSE 0 END) AS NULL_QUANTITY,
    COUNT(*) AS TOTAL_ROWS
FROM TPCH_ANALYTICS_DB.STAGING.LINEITEM;

-- Kiểm tra duplicates
-- Kiểm tra duplicate orders
SELECT 
    O_ORDERKEY,
    COUNT(*) AS DUPLICATE_COUNT
FROM TPCH_ANALYTICS_DB.STAGING.ORDERS
GROUP BY O_ORDERKEY
HAVING COUNT(*) > 1;

-- Kiểm tra duplicate customers
SELECT 
    C_CUSTKEY,
    COUNT(*) AS DUPLICATE_COUNT
FROM TPCH_ANALYTICS_DB.STAGING.CUSTOMER
GROUP BY C_CUSTKEY
HAVING COUNT(*) > 1;

-- Kiểm tra duplicate lineitems
SELECT 
    L_ORDERKEY,
    L_LINENUMBER,
    COUNT(*) AS DUPLICATE_COUNT
FROM TPCH_ANALYTICS_DB.STAGING.LINEITEM
GROUP BY L_ORDERKEY, L_LINENUMBER
HAVING COUNT(*) > 1;

-- Kiểm tra referential integrity
-- Kiểm tra ORDERS có CUSTKEY không tồn tại trong CUSTOMER
SELECT 
    'ORDERS with invalid CUSTKEY' AS CHECK_TYPE,
    COUNT(*) AS VIOLATION_COUNT
FROM TPCH_ANALYTICS_DB.STAGING.ORDERS O
LEFT JOIN TPCH_ANALYTICS_DB.STAGING.CUSTOMER C ON O.O_CUSTKEY = C.C_CUSTKEY
WHERE C.C_CUSTKEY IS NULL

UNION ALL

-- Kiểm tra LINEITEM có ORDERKEY không tồn tại trong ORDERS
SELECT 
    'LINEITEM with invalid ORDERKEY' AS CHECK_TYPE,
    COUNT(*) AS VIOLATION_COUNT
FROM TPCH_ANALYTICS_DB.STAGING.LINEITEM L
LEFT JOIN TPCH_ANALYTICS_DB.STAGING.ORDERS O ON L.L_ORDERKEY = O.O_ORDERKEY
WHERE O.O_ORDERKEY IS NULL

UNION ALL

-- Kiểm tra LINEITEM có PARTKEY không tồn tại trong PART
SELECT 
    'LINEITEM with invalid PARTKEY' AS CHECK_TYPE,
    COUNT(*) AS VIOLATION_COUNT
FROM TPCH_ANALYTICS_DB.STAGING.LINEITEM L
LEFT JOIN TPCH_ANALYTICS_DB.STAGING.PART P ON L.L_PARTKEY = P.P_PARTKEY
WHERE P.P_PARTKEY IS NULL

UNION ALL

-- Kiểm tra CUSTOMER có NATIONKEY không tồn tại trong NATION
SELECT 
    'CUSTOMER with invalid NATIONKEY' AS CHECK_TYPE,
    COUNT(*) AS VIOLATION_COUNT
FROM TPCH_ANALYTICS_DB.STAGING.CUSTOMER C
LEFT JOIN TPCH_ANALYTICS_DB.STAGING.NATION N ON C.C_NATIONKEY = N.N_NATIONKEY
WHERE N.N_NATIONKEY IS NULL;

-- Kiểm tra giá trị âm hoặc không hợp lệ
-- Kiểm tra giá trị âm trong ORDERS
SELECT 
    'ORDERS with negative TOTALPRICE' AS CHECK_TYPE,
    COUNT(*) AS VIOLATION_COUNT
FROM TPCH_ANALYTICS_DB.STAGING.ORDERS
WHERE O_TOTALPRICE < 0

UNION ALL

-- Kiểm tra giá trị âm trong LINEITEM
SELECT 
    'LINEITEM with negative QUANTITY' AS CHECK_TYPE,
    COUNT(*) AS VIOLATION_COUNT
FROM TPCH_ANALYTICS_DB.STAGING.LINEITEM
WHERE L_QUANTITY < 0

UNION ALL

SELECT 
    'LINEITEM with negative EXTENDEDPRICE' AS CHECK_TYPE,
    COUNT(*) AS VIOLATION_COUNT
FROM TPCH_ANALYTICS_DB.STAGING.LINEITEM
WHERE L_EXTENDEDPRICE < 0

UNION ALL

SELECT 
    'LINEITEM with DISCOUNT < 0 or > 1' AS CHECK_TYPE,
    COUNT(*) AS VIOLATION_COUNT
FROM TPCH_ANALYTICS_DB.STAGING.LINEITEM
WHERE L_DISCOUNT < 0 OR L_DISCOUNT > 1;

-- Kiểm tra date consistency
-- Kiểm tra SHIPDATE phải sau ORDERDATE
SELECT 
    'LINEITEM with SHIPDATE before ORDERDATE' AS CHECK_TYPE,
    COUNT(*) AS VIOLATION_COUNT
FROM TPCH_ANALYTICS_DB.STAGING.LINEITEM L
JOIN TPCH_ANALYTICS_DB.STAGING.ORDERS O ON L.L_ORDERKEY = O.O_ORDERKEY
WHERE L.L_SHIPDATE < O.O_ORDERDATE;

-- ============================================================================
-- 3.3 PERFORMANCE OPTIMIZATION VỚI EXPLAIN
-- ============================================================================

-- Sử dụng EXPLAIN để phân tích query execution plan
-- Query phức tạp: Customer orders với revenue
EXPLAIN USING TABULAR
SELECT 
    C.C_NAME AS CUSTOMER_NAME,
    N.N_NAME AS NATION,
    COUNT(DISTINCT O.O_ORDERKEY) AS TOTAL_ORDERS,
    SUM(O.O_TOTALPRICE) AS TOTAL_REVENUE,
    AVG(O.O_TOTALPRICE) AS AVG_ORDER_VALUE
FROM TPCH_ANALYTICS_DB.STAGING.CUSTOMER C
JOIN TPCH_ANALYTICS_DB.STAGING.NATION N ON C.C_NATIONKEY = N.N_NATIONKEY
JOIN TPCH_ANALYTICS_DB.STAGING.ORDERS O ON C.C_CUSTKEY = O.O_CUSTKEY
WHERE O.O_ORDERDATE >= DATEADD('year', -2, CURRENT_DATE())
GROUP BY C.C_NAME, N.N_NAME
HAVING SUM(O.O_TOTALPRICE) > 100000
ORDER BY TOTAL_REVENUE DESC
LIMIT 100;

-- Query phức tạp: Top products với supplier info
EXPLAIN USING TABULAR
SELECT 
    P.P_NAME AS PRODUCT_NAME,
    P.P_BRAND AS BRAND,
    S.S_NAME AS SUPPLIER_NAME,
    N.N_NAME AS SUPPLIER_NATION,
    SUM(L.L_QUANTITY) AS TOTAL_QUANTITY,
    SUM(L.L_EXTENDEDPRICE) AS TOTAL_REVENUE
FROM TPCH_ANALYTICS_DB.STAGING.LINEITEM L
JOIN TPCH_ANALYTICS_DB.STAGING.PART P ON L.L_PARTKEY = P.P_PARTKEY
JOIN TPCH_ANALYTICS_DB.STAGING.SUPPLIER S ON L.L_SUPPKEY = S.S_SUPPKEY
JOIN TPCH_ANALYTICS_DB.STAGING.NATION N ON S.S_NATIONKEY = N.N_NATIONKEY
JOIN TPCH_ANALYTICS_DB.STAGING.ORDERS O ON L.L_ORDERKEY = O.O_ORDERKEY
WHERE O.O_ORDERDATE >= DATEADD('year', -1, CURRENT_DATE())
GROUP BY P.P_NAME, P.P_BRAND, S.S_NAME, N.N_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 50;

-- Phân tích query performance với query profile
-- Lưu ý: Query Profile có thể xem trong Snowsight UI sau khi chạy query
-- Dưới đây là query để kiểm tra query history

-- Kiểm tra Query History (chạy query trên để xem trong history)
SELECT 
    QUERY_ID,
    QUERY_TEXT,
    DATABASE_NAME,
    SCHEMA_NAME,
    USER_NAME,
    ROLE_NAME,
    EXECUTION_STATUS,
    START_TIME,
    END_TIME,
    TOTAL_ELAPSED_TIME / 1000 AS ELAPSED_TIME_SECONDS,
    BYTES_SCANNED,
    ROWS_PRODUCED,
    PARTITIONS_SCANNED,
    PARTITIONS_TOTAL
FROM TABLE(INFORMATION_SCHEMA.QUERY_HISTORY())
WHERE DATABASE_NAME = 'TPCH_ANALYTICS_DB'
    AND START_TIME >= DATEADD('hour', -24, CURRENT_TIMESTAMP())
    AND EXECUTION_STATUS = 'SUCCESS'
ORDER BY START_TIME DESC
LIMIT 20;

-- Kiểm tra table statistics và clustering keys
-- Xem clustering information
SHOW TABLES LIKE 'ORDERS' IN SCHEMA TPCH_ANALYTICS_DB.STAGING;
SHOW TABLES LIKE 'LINEITEM' IN SCHEMA TPCH_ANALYTICS_DB.STAGING;
SHOW TABLES LIKE 'CUSTOMER' IN SCHEMA TPCH_ANALYTICS_DB.STAGING;

-- Query để xem table size và row count
SELECT 
    TABLE_CATALOG AS DATABASE_NAME,
    TABLE_SCHEMA AS SCHEMA_NAME,
    TABLE_NAME,
    ROW_COUNT,
    BYTES,
    ROUND(BYTES / 1024 / 1024, 2) AS SIZE_MB
FROM TPCH_ANALYTICS_DB.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA IN ('STAGING', 'SILVER', 'GOLD')
ORDER BY BYTES DESC;

-- Recommendations cho performance optimization
-- 1. Kiểm tra nếu cần clustering keys cho các bảng lớn
-- 2. Kiểm tra nếu cần materialized views cho các query thường dùng
-- 3. Xem xét sử dụng query result cache cho các query tĩnh
-- 4. Xem xét partitioning cho các bảng date-based queries

-- ============================================================================
-- 3.4 DATA DISTRIBUTION ANALYSIS
-- ============================================================================

-- Phân tích distribution của các trường quan trọng
-- Distribution của ORDERSTATUS
SELECT 
    O_ORDERSTATUS,
    COUNT(*) AS COUNT,
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (), 2) AS PERCENTAGE
FROM TPCH_ANALYTICS_DB.STAGING.ORDERS
GROUP BY O_ORDERSTATUS
ORDER BY COUNT DESC;

-- Distribution của MKTSEGMENT
SELECT 
    C_MKTSEGMENT,
    COUNT(*) AS COUNT,
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (), 2) AS PERCENTAGE
FROM TPCH_ANALYTICS_DB.STAGING.CUSTOMER
GROUP BY C_MKTSEGMENT
ORDER BY COUNT DESC;

-- Distribution của ORDERPRIORITY
SELECT 
    O_ORDERPRIORITY,
    COUNT(*) AS COUNT,
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (), 2) AS PERCENTAGE
FROM TPCH_ANALYTICS_DB.STAGING.ORDERS
GROUP BY O_ORDERPRIORITY
ORDER BY COUNT DESC;

