-- ============================================================================
-- PHẦN 4: SECURITY - MASKING POLICIES & DATA SHARING
-- ============================================================================
-- TPC-H Analytics Project - Data Masking, Security Policies, Secure Sharing
-- ============================================================================

USE DATABASE TPCH_ANALYTICS_DB;

-- ============================================================================
-- 4.1 TẠO BẢNG VỚI SENSITIVE DATA
-- ============================================================================

USE SCHEMA TPCH_ANALYTICS_DB.ANALYTICS;

-- Tạo bảng customers với thông tin nhạy cảm
CREATE OR REPLACE TABLE TPCH_ANALYTICS_DB.ANALYTICS.CUSTOMER_SENSITIVE AS
SELECT 
    C.C_CUSTKEY,
    C.C_NAME,
    C.C_ADDRESS,
    C.C_PHONE,
    C.C_ACCTBAL,
    N.N_NAME AS NATION,
    R.R_NAME AS REGION,
    C.C_MKTSEGMENT,
    -- Thêm thông tin nhạy cảm (giả lập)
    'customer_' || C.C_CUSTKEY || '@company.com' AS EMAIL,
    LPAD(ABS(MOD(C.C_CUSTKEY * 123456789, 1000000000)), 9, '0') AS SSN_LAST_9
FROM TPCH_ANALYTICS_DB.STAGING.CUSTOMER C
JOIN TPCH_ANALYTICS_DB.STAGING.NATION N ON C.C_NATIONKEY = N.N_NATIONKEY
JOIN TPCH_ANALYTICS_DB.STAGING.REGION R ON N.N_REGIONKEY = R.R_REGIONKEY;

-- Verify bảng đã tạo
SELECT COUNT(*) AS ROW_COUNT FROM TPCH_ANALYTICS_DB.ANALYTICS.CUSTOMER_SENSITIVE;
SELECT * FROM TPCH_ANALYTICS_DB.ANALYTICS.CUSTOMER_SENSITIVE LIMIT 5;

-- ============================================================================
-- 4.2 TẠO MASKING POLICIES
-- ============================================================================

USE SCHEMA TPCH_ANALYTICS_DB.ANALYTICS;

-- Masking policy cho EMAIL - Mask toàn bộ ngoại trừ domain
CREATE OR REPLACE MASKING POLICY TPCH_ANALYTICS_DB.ANALYTICS.MASK_EMAIL AS
    (VAL VARCHAR) RETURNS VARCHAR ->
    CASE
        WHEN CURRENT_ROLE() IN ('TPCH_ADMIN', 'ACCOUNTADMIN') THEN VAL
        WHEN CURRENT_ROLE() = 'TPCH_ANALYST' THEN 
            REGEXP_REPLACE(VAL, '(.*?)@', '****@')
        ELSE '***MASKED***'
    END;

-- Masking policy cho PHONE - Chỉ hiển thị 4 số cuối
CREATE OR REPLACE MASKING POLICY TPCH_ANALYTICS_DB.ANALYTICS.MASK_PHONE AS
    (VAL VARCHAR) RETURNS VARCHAR ->
    CASE
        WHEN CURRENT_ROLE() IN ('TPCH_ADMIN', 'ACCOUNTADMIN') THEN VAL
        WHEN CURRENT_ROLE() = 'TPCH_ANALYST' THEN 
            '***-***-' || RIGHT(VAL, 4)
        ELSE '***MASKED***'
    END;

-- Masking policy cho SSN - Chỉ hiển thị 3 số cuối
CREATE OR REPLACE MASKING POLICY TPCH_ANALYTICS_DB.ANALYTICS.MASK_SSN AS
    (VAL VARCHAR) RETURNS VARCHAR ->
    CASE
        WHEN CURRENT_ROLE() IN ('TPCH_ADMIN', 'ACCOUNTADMIN') THEN VAL
        WHEN CURRENT_ROLE() = 'TPCH_ANALYST' THEN 
            '******' || RIGHT(VAL, 3)
        ELSE '***MASKED***'
    END;

-- Masking policy cho ACCOUNT BALANCE - Round to nearest 1000
CREATE OR REPLACE MASKING POLICY TPCH_ANALYTICS_DB.ANALYTICS.MASK_ACCTBAL AS
    (VAL NUMBER) RETURNS NUMBER ->
    CASE
        WHEN CURRENT_ROLE() IN ('TPCH_ADMIN', 'ACCOUNTADMIN', 'TPCH_ANALYST') THEN VAL
        ELSE ROUND(VAL, -3)  -- Round to nearest 1000
    END;

-- Masking policy cho ADDRESS - Mask toàn bộ
CREATE OR REPLACE MASKING POLICY TPCH_ANALYTICS_DB.ANALYTICS.MASK_ADDRESS AS
    (VAL VARCHAR) RETURNS VARCHAR ->
    CASE
        WHEN CURRENT_ROLE() IN ('TPCH_ADMIN', 'ACCOUNTADMIN') THEN VAL
        ELSE '***MASKED***'
    END;

-- ============================================================================
-- 4.3 APPLY MASKING POLICIES
-- ============================================================================

-- Apply policies vào columns
ALTER TABLE TPCH_ANALYTICS_DB.ANALYTICS.CUSTOMER_SENSITIVE
    MODIFY COLUMN EMAIL SET MASKING POLICY TPCH_ANALYTICS_DB.ANALYTICS.MASK_EMAIL;

ALTER TABLE TPCH_ANALYTICS_DB.ANALYTICS.CUSTOMER_SENSITIVE
    MODIFY COLUMN C_PHONE SET MASKING POLICY TPCH_ANALYTICS_DB.ANALYTICS.MASK_PHONE;

ALTER TABLE TPCH_ANALYTICS_DB.ANALYTICS.CUSTOMER_SENSITIVE
    MODIFY COLUMN SSN_LAST_9 SET MASKING POLICY TPCH_ANALYTICS_DB.ANALYTICS.MASK_SSN;

ALTER TABLE TPCH_ANALYTICS_DB.ANALYTICS.CUSTOMER_SENSITIVE
    MODIFY COLUMN C_ACCTBAL SET MASKING POLICY TPCH_ANALYTICS_DB.ANALYTICS.MASK_ACCTBAL;

ALTER TABLE TPCH_ANALYTICS_DB.ANALYTICS.CUSTOMER_SENSITIVE
    MODIFY COLUMN C_ADDRESS SET MASKING POLICY TPCH_ANALYTICS_DB.ANALYTICS.MASK_ADDRESS;

-- Verify policies đã apply
SELECT 
    POLICY_NAME,
    POLICY_KIND,
    APPLY_ON
FROM TABLE(INFORMATION_SCHEMA.POLICY_REFERENCES(
    REF_ENTITY_NAME => 'TPCH_ANALYTICS_DB.ANALYTICS.CUSTOMER_SENSITIVE',
    REF_ENTITY_DOMAIN => 'table'
));

-- ============================================================================
-- 4.4 TEST MASKING POLICIES
-- ============================================================================

-- Lưu ý: Để test masking policies, bạn cần switch role và query lại
-- Ví dụ:
-- USE ROLE TPCH_ADMIN;
-- SELECT C_CUSTKEY, C_NAME, EMAIL, C_PHONE, SSN_LAST_9, C_ACCTBAL FROM TPCH_ANALYTICS_DB.ANALYTICS.CUSTOMER_SENSITIVE LIMIT 5;
--
-- USE ROLE TPCH_ANALYST;
-- SELECT C_CUSTKEY, C_NAME, EMAIL, C_PHONE, SSN_LAST_9, C_ACCTBAL FROM TPCH_ANALYTICS_DB.ANALYTICS.CUSTOMER_SENSITIVE LIMIT 5;
--
-- USE ROLE TPCH_VIEWER;
-- SELECT C_CUSTKEY, C_NAME, EMAIL, C_PHONE, SSN_LAST_9, C_ACCTBAL FROM TPCH_ANALYTICS_DB.ANALYTICS.CUSTOMER_SENSITIVE LIMIT 5;

-- Test với role hiện tại (giả sử là ADMIN)
-- Test với role ADMIN (xem full data)
SELECT 
    'ADMIN ROLE' AS TEST_ROLE,
    C_CUSTKEY,
    C_NAME,
    EMAIL,
    C_PHONE,
    SSN_LAST_9,
    C_ACCTBAL,
    C_ADDRESS
FROM TPCH_ANALYTICS_DB.ANALYTICS.CUSTOMER_SENSITIVE
LIMIT 5;

-- Grant quyền SELECT cho các roles để test
GRANT SELECT ON TABLE TPCH_ANALYTICS_DB.ANALYTICS.CUSTOMER_SENSITIVE TO ROLE TPCH_ADMIN;
GRANT SELECT ON TABLE TPCH_ANALYTICS_DB.ANALYTICS.CUSTOMER_SENSITIVE TO ROLE TPCH_ANALYST;
GRANT SELECT ON TABLE TPCH_ANALYTICS_DB.ANALYTICS.CUSTOMER_SENSITIVE TO ROLE TPCH_VIEWER;

-- ============================================================================
-- 4.5 SECURE DATA SHARING
-- ============================================================================

USE SCHEMA TPCH_ANALYTICS_DB.REPORTS;

-- Tạo secure view cho external sharing
-- Note: Không bao gồm EMAIL, PHONE, SSN, BALANCE, ADDRESS
CREATE OR REPLACE SECURE VIEW TPCH_ANALYTICS_DB.REPORTS.VW_CUSTOMER_PUBLIC AS
SELECT 
    CS.C_CUSTKEY,
    CS.C_NAME,
    CS.NATION,
    CS.REGION,
    CS.C_MKTSEGMENT
FROM TPCH_ANALYTICS_DB.ANALYTICS.CUSTOMER_SENSITIVE CS;

-- Tạo view cho customer summary (aggregated data)
CREATE OR REPLACE SECURE VIEW TPCH_ANALYTICS_DB.REPORTS.VW_CUSTOMER_SUMMARY AS
SELECT 
    CL.C_CUSTKEY,
    CL.C_NAME,
    CL.C_NATION_NAME AS NATION,
    CL.C_REGION_NAME AS REGION,
    CL.C_MKTSEGMENT,
    CL.TOTAL_ORDERS,
    CL.TOTAL_SPENT,
    CL.AVG_ORDER_VALUE,
    CL.CUSTOMER_TIER,
    CL.IS_ACTIVE
FROM TPCH_ANALYTICS_DB.GOLD.CUSTOMER_LTV CL;

-- Tạo view cho daily sales summary
CREATE OR REPLACE SECURE VIEW TPCH_ANALYTICS_DB.REPORTS.VW_DAILY_SALES_SUMMARY AS
SELECT 
    SUMMARY_DATE,
    ORDER_YEAR,
    ORDER_MONTH,
    ORDER_QUARTER,
    TOTAL_ORDERS,
    TOTAL_CUSTOMERS,
    TOTAL_REVENUE,
    AVG_ORDER_VALUE,
    MIN_ORDER_VALUE,
    MAX_ORDER_VALUE
FROM TPCH_ANALYTICS_DB.GOLD.DAILY_SALES_SUMMARY;

-- Grant quyền trên views cho các roles
GRANT SELECT ON VIEW TPCH_ANALYTICS_DB.REPORTS.VW_CUSTOMER_PUBLIC TO ROLE TPCH_ADMIN;
GRANT SELECT ON VIEW TPCH_ANALYTICS_DB.REPORTS.VW_CUSTOMER_PUBLIC TO ROLE TPCH_ANALYST;
GRANT SELECT ON VIEW TPCH_ANALYTICS_DB.REPORTS.VW_CUSTOMER_PUBLIC TO ROLE TPCH_VIEWER;

GRANT SELECT ON VIEW TPCH_ANALYTICS_DB.REPORTS.VW_CUSTOMER_SUMMARY TO ROLE TPCH_ADMIN;
GRANT SELECT ON VIEW TPCH_ANALYTICS_DB.REPORTS.VW_CUSTOMER_SUMMARY TO ROLE TPCH_ANALYST;
GRANT SELECT ON VIEW TPCH_ANALYTICS_DB.REPORTS.VW_CUSTOMER_SUMMARY TO ROLE TPCH_VIEWER;

GRANT SELECT ON VIEW TPCH_ANALYTICS_DB.REPORTS.VW_DAILY_SALES_SUMMARY TO ROLE TPCH_ADMIN;
GRANT SELECT ON VIEW TPCH_ANALYTICS_DB.REPORTS.VW_DAILY_SALES_SUMMARY TO ROLE TPCH_ANALYST;
GRANT SELECT ON VIEW TPCH_ANALYTICS_DB.REPORTS.VW_DAILY_SALES_SUMMARY TO ROLE TPCH_VIEWER;

-- Verify views đã tạo
SHOW VIEWS IN SCHEMA TPCH_ANALYTICS_DB.REPORTS;

-- Test views
SELECT * FROM TPCH_ANALYTICS_DB.REPORTS.VW_CUSTOMER_PUBLIC LIMIT 5;
SELECT * FROM TPCH_ANALYTICS_DB.REPORTS.VW_CUSTOMER_SUMMARY LIMIT 5;
SELECT * FROM TPCH_ANALYTICS_DB.REPORTS.VW_DAILY_SALES_SUMMARY ORDER BY SUMMARY_DATE DESC LIMIT 10;

-- ============================================================================
-- 4.6 SECURE DATA SHARING (SHARE OBJECT)
-- ============================================================================

-- Lưu ý: Secure data sharing trong Snowflake yêu cầu ACCOUNTADMIN role
-- Dưới đây là template, cần chạy với ACCOUNTADMIN role

-- Tạo share object (chạy với ACCOUNTADMIN)
-- CREATE SHARE TPCH_CUSTOMER_SHARE;
-- 
-- -- Grant usage trên database (nếu share external account)
-- -- GRANT USAGE ON DATABASE TPCH_ANALYTICS_DB TO SHARE TPCH_CUSTOMER_SHARE;
-- 
-- -- Grant usage trên schema
-- GRANT USAGE ON SCHEMA TPCH_ANALYTICS_DB.REPORTS TO SHARE TPCH_CUSTOMER_SHARE;
-- 
-- -- Grant select trên secure view
-- GRANT SELECT ON VIEW TPCH_ANALYTICS_DB.REPORTS.VW_CUSTOMER_PUBLIC TO SHARE TPCH_CUSTOMER_SHARE;
-- GRANT SELECT ON VIEW TPCH_ANALYTICS_DB.REPORTS.VW_DAILY_SALES_SUMMARY TO SHARE TPCH_CUSTOMER_SHARE;
-- 
-- -- Add consumer account (replace với account identifier thực tế)
-- -- ALTER SHARE TPCH_CUSTOMER_SHARE ADD ACCOUNTS = <consumer_account_identifier>;
-- 
-- -- View share details
-- SHOW SHARES LIKE 'TPCH_CUSTOMER_SHARE';
-- DESC SHARE TPCH_CUSTOMER_SHARE;

-- Comment out vì cần ACCOUNTADMIN role
-- Để test, bạn có thể tạo share và add vào cùng account để test

-- ============================================================================
-- 4.7 SUMMARY - SECURITY CHECKLIST
-- ============================================================================

-- Kiểm tra tất cả masking policies
SHOW MASKING POLICIES IN SCHEMA TPCH_ANALYTICS_DB.ANALYTICS;

-- Kiểm tra tất cả secure views
SHOW VIEWS IN SCHEMA TPCH_ANALYTICS_DB.REPORTS;

-- Kiểm tra grants trên sensitive table
SHOW GRANTS ON TABLE TPCH_ANALYTICS_DB.ANALYTICS.CUSTOMER_SENSITIVE;

-- Kiểm tra grants trên secure views
SHOW GRANTS ON VIEW TPCH_ANALYTICS_DB.REPORTS.VW_CUSTOMER_PUBLIC;
SHOW GRANTS ON VIEW TPCH_ANALYTICS_DB.REPORTS.VW_CUSTOMER_SUMMARY;
SHOW GRANTS ON VIEW TPCH_ANALYTICS_DB.REPORTS.VW_DAILY_SALES_SUMMARY;

